name: Build jar

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Upload jar
        uses: actions/upload-artifact@v2
        with:
          name: cubingPaper
          path: target/cubingpaper-1.8.8-R0.1-SNAPSHOT.jar
      - name: Create Release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            artifacts: target/cubingpaper-1.8.8-R0.1-SNAPSHOT.jar
            draft: false
            prerelease: true
            releaseName: ${{ github.ref }}
            releaseNotes: |
                This is an automated release.



