name: Build Template

on:
  workflow_call:
    inputs:
      build_only:
        required: false
        type: boolean
        default: false
    secrets:
      NEXUS_USERNAME:
        required: false
      NEXUS_PASSWORD:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: setup-java 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
        
    - name: Set Git user and email
      run: |
        git config --global user.name "speedcubing"
        git config --global user.email "git@speedcubing.top"

    - name: Run build.sh
      run: |
        chmod +x ./build.sh
        ./build.sh

    - name: upload-artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: ./CubingPaper-Server/target/cubingpaper-1.8.8-R0.1-SNAPSHOT.jar

    - name: setup ~/.m2/settings.xml
      if: ${{ !inputs.build_only }}
      run: |
        mkdir -p ~/.m2
        cat > ~/.m2/settings.xml <<EOF
        <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
          <servers>
            <server>
              <id>speedcubing-public-projects-release</id>
              <username>${{ secrets.NEXUS_USERNAME }}</username>
              <password>${{ secrets.NEXUS_PASSWORD }}</password>
            </server>
            <server>
              <id>speedcubing-public-projects-snapshot</id>
              <username>${{ secrets.NEXUS_USERNAME }}</username>
              <password>${{ secrets.NEXUS_PASSWORD }}</password>
            </server>
          </servers>
        </settings>
        EOF

    - name: Deploy to Nexus
      if: ${{ !inputs.build_only }}
      run: |
        mvn deploy -B --no-transfer-progress -DskipTests
